import type { Config } from "tailwindcss";

// Design tokens migrated verbatim from curio_system/DESIGN.md and the
// curio_landing_home / curio_explore_feed / curio_course_detail_locked
// Stitch exports (all three used an identical inline tailwind.config).
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "outline-variant": "#5a4136",
        "secondary-fixed-dim": "#87dd00",
        tertiary: "#ddb7ff",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed": "#9bfc00",
        "on-tertiary-fixed-variant": "#6900b3",
        "on-secondary-container": "#427000",
        "primary-fixed": "#ffdbcc",
        "on-tertiary": "#490080",
        "tertiary-fixed-dim": "#ddb7ff",
        "surface-dim": "#131313",
        "primary-container": "#ff6b00",
        "on-primary-fixed": "#351000",
        outline: "#a98a7d",
        surface: "#131313",
        "tertiary-fixed": "#f0dbff",
        "on-secondary-fixed": "#0f2000",
        "on-tertiary-fixed": "#2c0051",
        "secondary-container": "#9bfc00",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#2e4f00",
        "on-primary-fixed-variant": "#7a3000",
        "inverse-primary": "#a04100",
        "tertiary-container": "#bd79ff",
        "primary-fixed-dim": "#ffb693",
        "surface-container": "#201f1f",
        "on-surface-variant": "#e2bfb0",
        error: "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "on-background": "#e5e2e1",
        primary: "#ffb693",
        "surface-variant": "#353534",
        secondary: "#ffffff",
        "on-tertiary-container": "#4a0081",
        "inverse-on-surface": "#313030",
        "on-secondary": "#1e3700",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#572000",
        "surface-tint": "#ffb693",
        background: "#131313",
        "surface-bright": "#3a3939",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-primary": "#561f00",
        "surface-container-highest": "#353534",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max-width": "1440px",
        "margin-mobile": "20px",
        gutter: "24px",
        unit: "4px",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max-width": "1440px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
} satisfies Config;
